name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY:$IMAGE_TAG .
        docker push $ECR_REGISTRY:$IMAGE_TAG

    - name: Check if Lambda function exists
      id: check-lambda
      run: |
        FUNCTION_NAME="lambda-function"
        aws lambda get-function --function-name $FUNCTION_NAME || echo "Function does not exist"
      continue-on-error: true

    - name: Create or Update Lambda function
      run: |
        FUNCTION_NAME="lambda-function"
        IMAGE_URI="${{ secrets.AWS_ECR_REGISTRY }}:${{ github.sha }}"

        if aws lambda get-function --function-name $FUNCTION_NAME; then
          echo "Updating existing Lambda function..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --image-uri $IMAGE_URI
        else
          echo "Creating new Lambda function..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --code ImageUri=$IMAGE_URI \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/myfunctionExecRole \
            --package-type Image
        fi
